### ISSUE TITLE
Example Please

### ISSUE THREAD

**Issue by tsinis** [bdlukaa/just_audio_libwinmedia#1]
Hey. @bdlukaa 

Thanks for your work! It's not an issue, but could you please provide an example project (counter with .wav sound on FAB tap, will be enough)? It may help all of us in future debugging and issue reporting. Also, it will probably add some pub points to your package. Thanks in advance!

**Comment by bdlukaa** [comment]
The example in just_audio is enough for it, isn't? https://github.com/ryanheise/just_audio/tree/master/just_audio/example

**Comment by tsinis** [comment]
Hey! Well, it's not directly related to this package but ok. I'm closing for now.
