### ISSUE TITLE
startLoop should be set to false on Linux

### ISSUE THREAD

**Issue by Yesterday17** [bdlukaa/just_audio_libwinmedia#6]
When calling constructor of `Player`:
https://github.com/bdlukaa/just_audio_libwinmedia/blob/21b43158e68eaa47abc9d783cc33b47e98e477ce/lib/src/just_audio_libwinmedia_real.dart#L50

`startLoop: !Platform.isLinux` must be add as the comment of `libwinmedia` suggests:
https://github.com/harmonoid/libwinmedia/blob/71a7f157a0d3ed9a6394e73de7585a7c9a3525fa/flutter/lib/src/player.dart#L147

**Comment by bdlukaa** [comment]
Why?

**Comment by Yesterday17** [comment]
`startLoop` on Linux calls `gtk_main`, which is unnecessary for audio playback.
